version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped

  speech-to-text:
    build: .
    container_name: speech-to-text
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: 